# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build
      - run: yarn build

      # Copy files over
      - run:
          name: Build archive
          command: npm pack && mv lbaquotes-discord-`node -p "require('./package.json').version"`.tgz /tmp/workspace/lbaquotes-discord.tgz

      # Store artifacts
      - store_artifacts:
          path: /tmp/workspace/lbaquotes-discord.tgz

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - lbaquotes-discord.tgz

  deploy:
    machine: 
      enabled: true
    # working_directory: ~/repo
    steps: 
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy Over SSH
          command: | 
              scp -r ~/tmp/workspace/* "$DROPLET_USER@$DROPLET_IP:$DROPLET_PATH"

workflows:
  version: 2
  build-and-deploy:
    jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches: 
                only: master
